---
title: "Variables over time per species"
format: html
editor: visual
---

```{r}
# Load the data
load("data/bound-data.Rdata")

# Load necessary libraries
library(dplyr)
library(ggplot2)

# Convert Week to a factor
datab$Week1 <- as.factor(datab$Week)
datab$Soil_humidity <-  as.numeric(datab$Soil_humidity)
datab$Species[datab$Species=="Amaranthus retroflexus "] <- "Amaranthus retroflexus" 
```

Plant height

```{r}
# Group by Species, Treatment, and Week and calculate mean plant height
meanheight_byweeks <- datab %>%
  group_by(Species, Treatment, Week) %>%
  summarise(Mean_plant_height = mean(Plant_height))

# Create a ggplot with facets for each species
ggplot(meanheight_byweeks, aes(x = Week, y = Mean_plant_height, color = Treatment, group = Treatment)) +
  geom_point() +
  geom_line() +
  theme_bw() +
  facet_wrap(~Species, scales = "free_y")+
labs(title = "Mean Plant Height Over Weeks",
       x = "Week",
       y = "Mean Plant Height") +
  theme(legend.position = "top", legend.box.background = element_rect(colour = "black")) # Facet by Species with free y-axis scales

```

Soil humidity

```{r}
# Group by Species, Treatment, and Week and calculate mean soil humidity
meanhumidity_byweeks <- datab %>%
    filter(!is.na(Soil_humidity)) %>%
  group_by(Species, Treatment, Week) %>%
  summarise(Mean_soil_humidity = mean(Soil_humidity))

# Create a ggplot with facets for each species 
ggplot(meanhumidity_byweeks, aes(x = Week, y = Mean_soil_humidity, color = Treatment, group = Treatment)) +
  geom_point() +
  geom_line() +
  theme_bw() +
  facet_wrap(~Species, scales = "free_y")+  # Facet by Species with free y-axis scales
labs(title = "Mean Soil Humidity Over Weeks",
       x = "Week",
       y = "Mean Soil Humidity") +
  theme(legend.position = "top", legend.box.background = element_rect(colour = "black"))
```

Leaf_number
```{r}
# Group by Species, Treatment, and Week and calculate mean leaf number
meanleafnumber_byweeks <- datab %>%
  filter(!is.na(Leaf_number)) %>%
  group_by(Species, Treatment, Week) %>%
  summarise(Mean_leaf_number = mean(Leaf_number))

# Create a ggplot with facets for each species
ggplot(meanleafnumber_byweeks, aes(x = Week, y = Mean_leaf_number, color = Treatment, group = Treatment)) +
  geom_point() +
  geom_line() +
  theme_bw() +
  facet_wrap(~Species, scales = "free_y")+  # Facet by Species with free y-axis scales
labs(title = "Mean Leaf Number Over Weeks",
       x = "Week",
       y = "Mean Leaf Number") +
  theme(legend.position = "top", legend.box.background = element_rect(colour = "black"))
```


Chlorophyll_content bar
```{r}
meanchlorophyll_byweeks <- datab %>%
  filter(!is.na(Chlorophyll_content)) %>%
  group_by(Species, Treatment, Week) %>%
  summarise(Mean_Chlorophyll = mean(Chlorophyll_content))
#barplot

ggplot(meanchlorophyll_byweeks, aes(x = Species, y = Mean_Chlorophyll, fill = Treatment, colour = Treatment)) +   geom_bar(stat = "identity", position = "dodge")+
  labs(title = "Mean Chlorophyll Content by Species and Treatment",
       x = "Species",
       y = "Mean Chlorophyll Content") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 60, vjust = 1, hjust=1))+
  scale_fill_brewer(palette="Set1") 
```


Aerial_fresh_weight #CHANGE GRAPH TYPE MAYBE BAR GRAPH
```{r}
# Group by Species, Treatment, and Week and calculate mean 
meanaerialfresh_byweeks <- datab %>%
  filter(!is.na(Aerial_fresh_weight)) %>%
  group_by(Species, Treatment) %>%
  summarise(Mean_Aerialfresh = mean(Aerial_fresh_weight))

#barplot

ggplot(meanaerialfresh_byweeks, aes(x = Species, y = Mean_Aerialfresh, fill = Treatment, colour = Treatment)) +   geom_bar(stat = "identity", position = "dodge")+
  labs(title = "Mean Aerial Fresh Weight by Species and Treatment",
       x = "Species",
       y = "Mean Aerial Fresh Weight") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 60, vjust = 1, hjust=1))+
  scale_fill_brewer(palette="Set1") 

```

Aerial_dry_weight
```{r}
# Group by Species, Treatment, and Week and calculate mean 
meanaerialdry_byweeks <- datab %>%
  filter(!is.na(Aerial_dry_weight)) %>%
  group_by(Species, Treatment) %>%
  summarise(Mean_Aerialdry = mean(Aerial_dry_weight))
#barplot

ggplot(meanaerialdry_byweeks, aes(x = Species, y = Mean_Aerialdry, fill = Treatment, colour = Treatment)) +   geom_bar(stat = "identity", position = "dodge")+
  labs(title = "Mean Aerial Dry Weight by Species and Treatment",
  x = "Species",
  y = "Mean Aerial Dry Weight") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 60, vjust = 1, hjust=1))+
  scale_fill_brewer(palette="Set1") 
```

Root_length 
```{r}
# Group by Species, Treatment, and Week and calculate mean 
meanroot_lenght <- datab %>%
  filter(!is.na(Root_length)) %>%
  group_by(Species, Treatment) %>%
  summarise(Mean_Rootlength = mean(Root_length))
#barplot

ggplot(meanroot_lenght, aes(x = Species, y = Mean_Rootlength, fill = Treatment, colour = Treatment)) +   geom_bar(stat = "identity", position = "dodge")+
  labs(title = "Mean Root Lenght by Species and Treatment",
  x = "Species",
  y = "Mean Root Lenght") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 60, vjust = 1, hjust=1))+
  scale_fill_brewer(palette="Set1")
```

Root_fresh_weight
```{r}
# Group by Species, Treatment, and Week and calculate mean 
meanroot_fresh <- datab %>%
  filter(!is.na(Roots_fresh_weight)) %>%
  group_by(Species, Treatment) %>%
  summarise(Mean_Rootfresh = mean(Roots_fresh_weight))
#barplot

ggplot(meanroot_fresh, aes(x = Species, y = Mean_Rootfresh, fill = Treatment, colour = Treatment)) +   geom_bar(stat = "identity", position = "dodge")+
  labs(title = "Mean Root Fresh Weight by Species and Treatment",
  x = "Species",
  y = "Mean Root Fresh Weight") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 60, vjust = 1, hjust=1))+
  scale_fill_brewer(palette="Set1")
```

Root_dry_weight
```{r}
# Group by Species, Treatment, and Week and calculate mean 
meanroot_dry <- datab %>%
  filter(!is.na(Roots_dry_weight)) %>%
  group_by(Species, Treatment) %>%
  summarise(Mean_Rootdry = mean(Roots_dry_weight))
#barplot

ggplot(meanroot_dry, aes(x = Species, y = Mean_Rootdry, fill = Treatment, colour = Treatment)) +   geom_bar(stat = "identity", position = "dodge")+
  labs(title = "Mean Root Dry Weight by Species and Treatment",
  x = "Species",
  y = "Mean Root Dry Weight") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 60, vjust = 1, hjust=1))+
  scale_fill_brewer(palette="Set1")
```


Statistical analysis

```{r}
library(agricolae)

datab$Soil_humidity <- as.numeric(datab$Soil_humidity)

st.sh <- datab %>%
  filter(!is.na(Soil_humidity)) %>%
  group_by(Species,Treatment,Week) %>%
  summarise(Mean.Soil.Humidity = mean(Soil_humidity),
            Median.Soil.Humidity = median(Soil_humidity),
            Variance.Soil.Humidity = var(Soil_humidity),
            Standard.Deviation.Soil.Humidity = sd(Soil_humidity))

datab <- tidyr::separate(datab,PlantId, c("sptr"), sep=3)

an <- aov(formula = datab$Plant_height ~ datab$sptr)
an
hsd <- TukeyHSD(an)
hsd
```

\`\`\`
